<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * EmprestimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmprestimoRepository extends EntityRepository
{
/*
	public function findByArmario($armario_id)
    {
        return $this
			->createQueryBuilder('p')
			->from('App:Armario','d')
			->setParameter('armario_id', $armario_id)
			->where('p.armario = :armario_id')
            ->orderBy('p.dataEmprestimo','DESC')
            //->setMaxResults(250*360) not working
            ->getQuery()
            ->execute();
    }
*/

}
